version: '3.4'

services:
  kitnugs:
    image: ${DOCKER_REGISTRY-}kitnugs
    build:
      context: .
      dockerfile: KitNugs/Dockerfile
    environment: 
        - "Serilog__MinimumLevel__Default=Debug"
    ports:
        - "8080:8080"
        - "8081:8081"
